# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a26d587eccddb2a1ae79a9ff72d1118b24af4b5c58d76721017877990ec75a5a1368ac9816cca3c61a08721ccd60c5df0d9c6c3088c0ba29ae99c1dad9c14a65

test:
  secret_key_base: 4c59ae8bc8a22d5587cfdc1fe12be2b3e770cc73b8f7afe60d00e7db323902209edf484086ad8b4073bfe3a7efebfe62c9175c9712c1a6a1a52dc8b3056e61a0

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
